//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6387
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace BBS {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class dataroot {
        
        private Markus[] markusField;
        
        private System.DateTime generatedField;
        
        private bool generatedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Markus")]
        public Markus[] Markus {
            get {
                return this.markusField;
            }
            set {
                this.markusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime generated {
            get {
                return this.generatedField;
            }
            set {
                this.generatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generatedSpecified {
            get {
                return this.generatedFieldSpecified;
            }
            set {
                this.generatedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Markus {
        
        private int medlNrField;
        
        private bool medlNrFieldSpecified;
        
        private int typAvMedlemField;
        
        private bool typAvMedlemFieldSpecified;
        
        private string förnamnField;
        
        private string efternamnField;
        
        private string adressField;
        
        private string postnrField;
        
        private string postadressField;
        
        private string emailField;
        
        private string telBostadField;
        
        private string telArbeteField;
        
        private string telMobilField;
        
        private string yrkeField;
        
        private string färdigheterField;
        
        private bool arbetsIntresseField;
        
        private System.DateTime bBSInträdeField;
        
        private bool bBSInträdeFieldSpecified;
        
        private System.DateTime bBSUtträdeField;
        
        private bool bBSUtträdeFieldSpecified;
        
        private int sBUNrField;
        
        private bool sBUNrFieldSpecified;
        
        private System.DateTime sBUDatumField;
        
        private bool sBUDatumFieldSpecified;
        
        private short nyckelField;
        
        private bool nyckelFieldSpecified;
        
        private string extranyckelField;
        
        private short depavgiftField;
        
        private bool depavgiftFieldSpecified;
        
        private int båtIdField;
        
        private int _MedlNrField;
        
        private bool _MedlNrFieldSpecified;
        
        private System.DateTime registerfördDatumField;
        
        private bool registerfördDatumFieldSpecified;
        
        private System.DateTime såldDatumField;
        
        private bool såldDatumFieldSpecified;
        
        private string typbeteckningField;
        
        private int typAvBåtField;
        
        private bool typAvBåtFieldSpecified;
        
        private string båtnamnField;
        
        private string försäkringsbolagField;
        
        private string försäkringsnummerField;
        
        private double lÖAField;
        
        private bool lÖAFieldSpecified;
        
        private double breddField;
        
        private bool breddFieldSpecified;
        
        private double djupgåendeField;
        
        private bool djupgåendeFieldSpecified;
        
        private double deplacementField;
        
        private bool deplacementFieldSpecified;
        
        private int torrsättningField;
        
        private bool torrsättningFieldSpecified;
        
        private int sjösättningField;
        
        private bool sjösättningFieldSpecified;
        
        private string reg_nrField;
        
        private string mastplatsField;
        
        private string mastlängdField;
        
        private string kajplatsField;
        
        private int typAvKajplatsField;
        
        private bool typAvKajplatsFieldSpecified;
        
        private string kajDebiteringField;
        
        private string upplagField;
        
        private int typAvUpplagField;
        
        private bool typAvUpplagFieldSpecified;
        
        private string upplagDebiteringField;
        
        private string isliggarplatsField;
        
        private string trailerplatsField;
        
        private int kopplMedlNrField;
        
        private bool kopplMedlNrFieldSpecified;
        
        private int kopplBåtIdField;
        
        private bool kopplBåtIdFieldSpecified;
        
        private int typAvÄgandeField;
        
        private bool typAvÄgandeFieldSpecified;
        
        private int kopplingParameterField;
        
        private bool kopplingParameterFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Medl-Nr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MedlNr {
            get {
                return this.medlNrField;
            }
            set {
                this.medlNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MedlNrSpecified {
            get {
                return this.medlNrFieldSpecified;
            }
            set {
                this.medlNrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TypAvMedlem {
            get {
                return this.typAvMedlemField;
            }
            set {
                this.typAvMedlemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypAvMedlemSpecified {
            get {
                return this.typAvMedlemFieldSpecified;
            }
            set {
                this.typAvMedlemFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Förnamn {
            get {
                return this.förnamnField;
            }
            set {
                this.förnamnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Efternamn {
            get {
                return this.efternamnField;
            }
            set {
                this.efternamnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Adress {
            get {
                return this.adressField;
            }
            set {
                this.adressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Post-nr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Postnr {
            get {
                return this.postnrField;
            }
            set {
                this.postnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Postadress {
            get {
                return this.postadressField;
            }
            set {
                this.postadressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TelBostad {
            get {
                return this.telBostadField;
            }
            set {
                this.telBostadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TelArbete {
            get {
                return this.telArbeteField;
            }
            set {
                this.telArbeteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TelMobil {
            get {
                return this.telMobilField;
            }
            set {
                this.telMobilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Yrke {
            get {
                return this.yrkeField;
            }
            set {
                this.yrkeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Färdigheter {
            get {
                return this.färdigheterField;
            }
            set {
                this.färdigheterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ArbetsIntresse {
            get {
                return this.arbetsIntresseField;
            }
            set {
                this.arbetsIntresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime BBSInträde {
            get {
                return this.bBSInträdeField;
            }
            set {
                this.bBSInträdeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BBSInträdeSpecified {
            get {
                return this.bBSInträdeFieldSpecified;
            }
            set {
                this.bBSInträdeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime BBSUtträde {
            get {
                return this.bBSUtträdeField;
            }
            set {
                this.bBSUtträdeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BBSUtträdeSpecified {
            get {
                return this.bBSUtträdeFieldSpecified;
            }
            set {
                this.bBSUtträdeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SBU-Nr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int SBUNr {
            get {
                return this.sBUNrField;
            }
            set {
                this.sBUNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SBUNrSpecified {
            get {
                return this.sBUNrFieldSpecified;
            }
            set {
                this.sBUNrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SBU-Datum", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime SBUDatum {
            get {
                return this.sBUDatumField;
            }
            set {
                this.sBUDatumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SBUDatumSpecified {
            get {
                return this.sBUDatumFieldSpecified;
            }
            set {
                this.sBUDatumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short Nyckel {
            get {
                return this.nyckelField;
            }
            set {
                this.nyckelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NyckelSpecified {
            get {
                return this.nyckelFieldSpecified;
            }
            set {
                this.nyckelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Extra nyckel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Extranyckel {
            get {
                return this.extranyckelField;
            }
            set {
                this.extranyckelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dep-avgift", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short Depavgift {
            get {
                return this.depavgiftField;
            }
            set {
                this.depavgiftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DepavgiftSpecified {
            get {
                return this.depavgiftFieldSpecified;
            }
            set {
                this.depavgiftFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int BåtId {
            get {
                return this.båtIdField;
            }
            set {
                this.båtIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_Medl-Nr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int _MedlNr {
            get {
                return this._MedlNrField;
            }
            set {
                this._MedlNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _MedlNrSpecified {
            get {
                return this._MedlNrFieldSpecified;
            }
            set {
                this._MedlNrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime RegisterfördDatum {
            get {
                return this.registerfördDatumField;
            }
            set {
                this.registerfördDatumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegisterfördDatumSpecified {
            get {
                return this.registerfördDatumFieldSpecified;
            }
            set {
                this.registerfördDatumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime SåldDatum {
            get {
                return this.såldDatumField;
            }
            set {
                this.såldDatumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SåldDatumSpecified {
            get {
                return this.såldDatumFieldSpecified;
            }
            set {
                this.såldDatumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Typbeteckning {
            get {
                return this.typbeteckningField;
            }
            set {
                this.typbeteckningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TypAvBåt {
            get {
                return this.typAvBåtField;
            }
            set {
                this.typAvBåtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypAvBåtSpecified {
            get {
                return this.typAvBåtFieldSpecified;
            }
            set {
                this.typAvBåtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Båtnamn {
            get {
                return this.båtnamnField;
            }
            set {
                this.båtnamnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Försäkringsbolag {
            get {
                return this.försäkringsbolagField;
            }
            set {
                this.försäkringsbolagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Försäkringsnummer {
            get {
                return this.försäkringsnummerField;
            }
            set {
                this.försäkringsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double LÖA {
            get {
                return this.lÖAField;
            }
            set {
                this.lÖAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LÖASpecified {
            get {
                return this.lÖAFieldSpecified;
            }
            set {
                this.lÖAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Bredd {
            get {
                return this.breddField;
            }
            set {
                this.breddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BreddSpecified {
            get {
                return this.breddFieldSpecified;
            }
            set {
                this.breddFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Djupgående {
            get {
                return this.djupgåendeField;
            }
            set {
                this.djupgåendeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DjupgåendeSpecified {
            get {
                return this.djupgåendeFieldSpecified;
            }
            set {
                this.djupgåendeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Deplacement {
            get {
                return this.deplacementField;
            }
            set {
                this.deplacementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeplacementSpecified {
            get {
                return this.deplacementFieldSpecified;
            }
            set {
                this.deplacementFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Torrsättning {
            get {
                return this.torrsättningField;
            }
            set {
                this.torrsättningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TorrsättningSpecified {
            get {
                return this.torrsättningFieldSpecified;
            }
            set {
                this.torrsättningFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Sjösättning {
            get {
                return this.sjösättningField;
            }
            set {
                this.sjösättningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SjösättningSpecified {
            get {
                return this.sjösättningFieldSpecified;
            }
            set {
                this.sjösättningFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Reg_nr {
            get {
                return this.reg_nrField;
            }
            set {
                this.reg_nrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mastplats {
            get {
                return this.mastplatsField;
            }
            set {
                this.mastplatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mastlängd {
            get {
                return this.mastlängdField;
            }
            set {
                this.mastlängdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Kajplats {
            get {
                return this.kajplatsField;
            }
            set {
                this.kajplatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TypAvKajplats {
            get {
                return this.typAvKajplatsField;
            }
            set {
                this.typAvKajplatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypAvKajplatsSpecified {
            get {
                return this.typAvKajplatsFieldSpecified;
            }
            set {
                this.typAvKajplatsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KajDebitering {
            get {
                return this.kajDebiteringField;
            }
            set {
                this.kajDebiteringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Upplag {
            get {
                return this.upplagField;
            }
            set {
                this.upplagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TypAvUpplag {
            get {
                return this.typAvUpplagField;
            }
            set {
                this.typAvUpplagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypAvUpplagSpecified {
            get {
                return this.typAvUpplagFieldSpecified;
            }
            set {
                this.typAvUpplagFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UpplagDebitering {
            get {
                return this.upplagDebiteringField;
            }
            set {
                this.upplagDebiteringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Isliggarplats {
            get {
                return this.isliggarplatsField;
            }
            set {
                this.isliggarplatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Trailerplats {
            get {
                return this.trailerplatsField;
            }
            set {
                this.trailerplatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Koppl-Medl-Nr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int KopplMedlNr {
            get {
                return this.kopplMedlNrField;
            }
            set {
                this.kopplMedlNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KopplMedlNrSpecified {
            get {
                return this.kopplMedlNrFieldSpecified;
            }
            set {
                this.kopplMedlNrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Koppl-BåtId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int KopplBåtId {
            get {
                return this.kopplBåtIdField;
            }
            set {
                this.kopplBåtIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KopplBåtIdSpecified {
            get {
                return this.kopplBåtIdFieldSpecified;
            }
            set {
                this.kopplBåtIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TypAvÄgande {
            get {
                return this.typAvÄgandeField;
            }
            set {
                this.typAvÄgandeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypAvÄgandeSpecified {
            get {
                return this.typAvÄgandeFieldSpecified;
            }
            set {
                this.typAvÄgandeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int KopplingParameter {
            get {
                return this.kopplingParameterField;
            }
            set {
                this.kopplingParameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KopplingParameterSpecified {
            get {
                return this.kopplingParameterFieldSpecified;
            }
            set {
                this.kopplingParameterFieldSpecified = value;
            }
        }
    }
}
